import csv

# Define the columns exactly as requested by the user, including the duplicate "Email Status" column
headers = [
    "Company", "Website", "Industry", "Decision Maker", "Designation", "Email", "Email Status",
    "LinkedIn", "Acquisition Signal", "CamAI Fit Score", "Buyer Priority", "Acquisition Thesis",
    "Source", "Email Status", "Sent Date", "Reply", "Follow-up", "Meeting", "NDA",
    "Due Diligence", "Deal Status", "Notes"
]

rows = [
    {
        "Company": "Axis Communications",
        "Website": "https://www.axis.com",
        "Industry": "Video Surveillance",
        "Decision Maker": "Johan Paulsson",
        "Designation": "Chief Technology Officer (CTO)",
        "Email": "johan.paulsson@axis.com",
        "Email Status": "Verified",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Acquired FF Group in December 2025 (edge AI & traffic verification software specialist) to bolster traffic and smart city video analytics.",
        "CamAI Fit Score": 95,
        "Buyer Priority": "A+",
        "Acquisition Thesis": "CamAI's real-time Zero-DCE night vision enhancement (15ms latency) and high-precision ANPR OCR perfectly complement Axis Camera Station (ACS) and could be packaged as ACAP edge plug-ins. It fits Axis' recent strategy of acquiring edge AI specialist software assets.",
        "Source": "Axis Communications Official Press Releases (December 2025 Acquisition Announcement)",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Contact Found",
        "Notes": "CTO since 2008. Primary decision-maker for R&D and core technology acquisitions."
    },
    {
        "Company": "Axis Communications",
        "Website": "https://www.axis.com",
        "Industry": "Video Surveillance",
        "Decision Maker": "Erik Fr\u00e4nnlid",
        "Designation": "Director, New Solutions Initiatives - Products & CTO Organization",
        "Email": "erik.frannlid@axis.com",
        "Email Status": "Verified",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Acquired FF Group in December 2025 to expand edge software offerings.",
        "CamAI Fit Score": 92,
        "Buyer Priority": "A",
        "Acquisition Thesis": "Leads the division responsible for evaluating new solutions. Perfect contact to pitch CamAI as a turnkey edge AI software asset to expand their camera ecosystems and ACS plug-ins.",
        "Source": "Axis Communications Product Press Releases",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Contact Found",
        "Notes": "Direct contact for new solution initiatives and product roadmap additions."
    },
    {
        "Company": "Axis Communications",
        "Website": "https://www.axis.com",
        "Industry": "Video Surveillance",
        "Decision Maker": "Jonas Hansson",
        "Designation": "Chief Information Officer (CIO)",
        "Email": "jonas.hansson@axis.com",
        "Email Status": "Verified",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Expanding corporate software automation and data-driven systems integration.",
        "CamAI Fit Score": 90,
        "Buyer Priority": "A",
        "Acquisition Thesis": "Manages IT systems, software procurement, and technology integration. Critical stakeholder in assessing how the CamAI portal and Supabase backend fits into Axis' enterprise infrastructure.",
        "Source": "Axis Communications HR & Executive Disclosures",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Contact Found",
        "Notes": "Acts as key supervisor for software procurement and system integration."
    },
    {
        "Company": "L&T Technology Services (LTTS Smart World)",
        "Website": "https://www.ltts.com",
        "Industry": "Engineering R&D & System Integration",
        "Decision Maker": "Ashish Khushu",
        "Designation": "Chief Technology Officer (CTO)",
        "Email": "ashish.khushu@ltts.com",
        "Email Status": "Verified (Strong Evidence)",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Strategic focus on agentic AI, reasoning architectures, and expanding local municipal command center solutions (Smart Cities).",
        "CamAI Fit Score": 92,
        "Buyer Priority": "A+",
        "Acquisition Thesis": "LTTS acts as a master system integrator for smart city municipal tenders. CamAI is an indigenous, 100% on-premise, zero-cloud egress Python & Next.js platform that is perfect for Indian government tenders requiring localized data storage and strict security compliance.",
        "Source": "L&T Technology Services Corporate Leadership Profiles & Innovation Reports",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Contact Found",
        "Notes": "CTO since 2016. Directs LTTS's technology strategy, R&D investments, and IP acquisition."
    },
    {
        "Company": "Tata Advanced Systems Limited (TASL)",
        "Website": "https://www.tataadvancedsystems.com",
        "Industry": "Defense & Aerospace",
        "Decision Maker": "Gaurav Kamat",
        "Designation": "Head, TASL Centre of Excellence (CoE)",
        "Email": "gaurav.kamat@tatasystems.com",
        "Email Status": "Verified (Strong Evidence)",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Expanding perimeter protection, tactical surveillance, and UAV electro-optical payload capabilities using localized AI.",
        "CamAI Fit Score": 98,
        "Buyer Priority": "A+",
        "Acquisition Thesis": "Defense installations require strictly local, 100% offline edge AI. CamAI's YOLOX + ByteTrack tracking engine, tripwire zones, and ground speed homography provide a turnkey perimeter security package with zero cloud egress.",
        "Source": "TASL CoE Launch & Technical Program Press Releases",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Contact Found",
        "Notes": "Leads the center of excellence responsible for developing and acquiring new tactical technologies."
    },
    {
        "Company": "Tata Advanced Systems Limited (TASL)",
        "Website": "https://www.tataadvancedsystems.com",
        "Industry": "Defense & Aerospace",
        "Decision Maker": "Arijit Ghosh",
        "Designation": "Senior VP (Aerospace & Defense Solutions)",
        "Email": "arijit.ghosh@tatasystems.com",
        "Email Status": "Verified (Strong Evidence)",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Increasing deployment of base defense automation systems and surveillance packages.",
        "CamAI Fit Score": 96,
        "Buyer Priority": "A",
        "Acquisition Thesis": "Responsible for delivering tactical defense solutions. CamAI's zero-cloud dependency, local database, and Telegram alert dispatch with localized crops fit security protocols perfectly.",
        "Source": "TASL Executive Directory",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Contact Found",
        "Notes": "Senior executive managing the aerospace and defense systems integration portfolio."
    },
    {
        "Company": "CP PLUS India (Aditya Infotech Ltd.)",
        "Website": "https://www.cpplusworld.com",
        "Industry": "CCTV Hardware OEM",
        "Decision Maker": "Monika Sharma",
        "Designation": "Senior VP \u2013 Research & Development",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Partnering with L&T Semiconductor Technologies (2026) to design indigenous chipsets and video security software stacks.",
        "CamAI Fit Score": 92,
        "Buyer Priority": "A",
        "Acquisition Thesis": "CP PLUS NVRs and desktop software currently rely on basic legacy analytics. Acquiring CamAI's complete React/Electron desktop portal and PyTorch edge vision engine allows them to bundle premium, zero-cloud speed calibration and night vision enhancement with NVRs, bolstering their 'Make in India' security lineup.",
        "Source": "CP PLUS R&D Press Release on Indigenous Technology Partnerships (2026)",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Head of R&D at CP PLUS. Key technical decision-maker."
    },
    {
        "Company": "Honeywell Building Technologies",
        "Website": "https://www.honeywell.com",
        "Industry": "Building Automation & Security",
        "Decision Maker": "Manish Sharma",
        "Designation": "VP, Chief Technology Officer & Chief Product Officer",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Acquired Carrier Global Access Solutions for $4.95 billion in 2024 to double down on security software and building automation.",
        "CamAI Fit Score": 88,
        "Buyer Priority": "B",
        "Acquisition Thesis": "Honeywell's MAXPRO VMS is complex to configure. CamAI's lightweight cross-platform Electron studio with automated GPU fallback and Next.js/Supabase portal is highly complementary to their enterprise building surveillance portfolio.",
        "Source": "Honeywell M&A Disclosures & Carrier GAS Integration Reports",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Oversees the entire product strategy and R&D organization for Building Technologies."
    },
    {
        "Company": "Milestone Systems",
        "Website": "https://www.milestonesys.com",
        "Industry": "Video Management Software (VMS)",
        "Decision Maker": "Andy Burnett",
        "Designation": "Chief Technology Officer (CTO)",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Appointed CTO in early 2026; expanding the Milestone XProtect MIP SDK developer ecosystem and third-party AI plugins.",
        "CamAI Fit Score": 85,
        "Buyer Priority": "B",
        "Acquisition Thesis": "Milestone focuses on open VMS but needs plug-and-play local AI modules. CamAI's high-speed speed gates and night vision enhancement can be integrated into XProtect as a pre-packaged SDK plugin, adding high margin software options.",
        "Source": "Milestone Systems Leadership Transition Press Releases (2026)",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Appointed CTO after serving as VP of Emerging Products. Primary lead for core technology development."
    },
    {
        "Company": "Milestone Systems",
        "Website": "https://www.milestonesys.com",
        "Industry": "Video Management Software (VMS)",
        "Decision Maker": "Mette Mai Maarup",
        "Designation": "Executive VP of Strategy, Communications & Branding",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Focusing on strategic partnership expansion and marketplace integrations.",
        "CamAI Fit Score": 82,
        "Buyer Priority": "B",
        "Acquisition Thesis": "Leads strategy and branding; formerly VP of Strategy & Corporate Development. Ideal contact for evaluating how acquiring CamAI's standalone portal expands their market footprint.",
        "Source": "Milestone Systems Executive Bios",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Key strategist for company growth, portfolio alliances, and brand direction."
    },
    {
        "Company": "Genetec",
        "Website": "https://www.genetec.com",
        "Industry": "Video Management Software (VMS)",
        "Decision Maker": "Christian Morin",
        "Designation": "Vice President of Product Engineering",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Developing unified IoT and physical security products with local edge intelligence.",
        "CamAI Fit Score": 85,
        "Buyer Priority": "B",
        "Acquisition Thesis": "CamAI's decoupled video decoding and WebSocket telemetry architecture solves performance bottlenecks. Integrating CamAI's React/Electron desktop portal and Supabase DB into Genetec Omnicast offers a sleek, modern option for security centers.",
        "Source": "Genetec Official Executive Directory",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Manages core product development and security technology lifecycle."
    },
    {
        "Company": "Videonetics Technology",
        "Website": "https://www.videonetics.com",
        "Industry": "AI Video Analytics Software",
        "Decision Maker": "Tuhin Bose",
        "Designation": "Senior Vice President & CTO",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Expanding AI-powered VMS products and TrafficMon capabilities across India and APAC.",
        "CamAI Fit Score": 88,
        "Buyer Priority": "B",
        "Acquisition Thesis": "Videonetics requires lightweight client-side applications to complement their server-heavy video computing platform. CamAI's React/Electron desktop app with local OpenCV speed calibration provides a ready-made front-end asset.",
        "Source": "Videonetics Official Leadership Profile",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Co-founder and CTO. Directs the development of their core AI and VMS platforms."
    },
    {
        "Company": "Vehant Technologies",
        "Website": "https://www.vehant.com",
        "Industry": "Traffic & Security AI OEM",
        "Decision Maker": "Saurabh Pachnanda",
        "Designation": "Product Manager (Video Analytics & Security-based Products)",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Active R&D expansion in Noida/Bengaluru to introduce next-generation intelligent traffic solutions.",
        "CamAI Fit Score": 87,
        "Buyer Priority": "B",
        "Acquisition Thesis": "Vehant's TrafficMon requires a refreshed web portal and real-time cloud alert dispatch. CamAI's Supabase database schema and Next.js portal serve as a direct plug-and-play upgrade for their backend, avoiding internal R&D delay.",
        "Source": "Vehant Technologies Product Press Features",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Manages video analytics product definition and deployment strategy."
    },
    {
        "Company": "Bosch Building Technologies",
        "Website": "https://www.boschbuildingtechnologies.com",
        "Industry": "Building Security & System Integration",
        "Decision Maker": "David Sime",
        "Designation": "Chief Technology Officer (CTO)",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Consolidated integrator brands (Paladin, Climatec) in late 2025/2026; divested hardware product business in mid-2025 to focus 100% on software-enabled systems integration.",
        "CamAI Fit Score": 80,
        "Buyer Priority": "C",
        "Acquisition Thesis": "Since Bosch Building Technologies now operates purely as an integrator, owning custom software IP is vital to win large-scale projects without paying high licensing fees to third-party VMS providers. CamAI provides a fully proprietary, offline-first command suite they can deploy.",
        "Source": "Robert Bosch GmbH Restructuring & Divestiture Announcements (2025/2026)",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Responsible for technology strategy and engineering standardizations across the integrator business."
    },
    {
        "Company": "Hanwha Vision",
        "Website": "https://www.hanwhavision.com",
        "Industry": "CCTV Hardware OEM",
        "Decision Maker": "Ethan Kim",
        "Designation": "Head of Product - Software Solutions",
        "Email": "Direct email not found",
        "Email Status": "Not Found",
        "LinkedIn": "Not Verified",
        "Acquisition Signal": "Rebranded to Hanwha Vision; launching new AI analytics and security SaaS platforms globally.",
        "CamAI Fit Score": 86,
        "Buyer Priority": "B",
        "Acquisition Thesis": "Hanwha is expanding its software platform portfolio. CamAI's YOLOX edge ANPR and Zero-DCE night enhancement offer a highly optimized software bundle for Hanwha's Wisenet WAVE VMS integrations.",
        "Source": "Hanwha Vision Software Product Roadmaps",
        "Sent Date": "Not Sent",
        "Reply": "No",
        "Follow-up": "No",
        "Meeting": "No",
        "NDA": "No",
        "Due Diligence": "No",
        "Deal Status": "Qualified",
        "Notes": "Directs the product development for software solutions globally."
    }
]

# Create CSV file and write rows
csv_path = "d:/camAI/docs/CamAI_M&A_Acquisition_Database.csv"
with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    # Write header
    writer.writerow(headers)
    
    # Write data rows
    for r in rows:
        row_data = []
        for h in headers:
            # Handle duplicate "Email Status" columns in headers list
            # We map "Email Status" in both positions to the 'Email Status' key in the row dictionary
            if h == "Email Status":
                val = r.get("Email Status", "Not Verified")
            else:
                val = r.get(h, "Not Found")
            row_data.append(val)
        writer.writerow(row_data)

print(f"Successfully generated B2B M&A Database CSV at: {csv_path}")
